### ISSUE TITLE
Modify bcSubset function in order to eliminate the spatial coordinates for the unwanted cells

### ISSUE THREAD

**Issue by tdido** [cnio-bu/beyondcell#12]
In GitLab by @cfustero on May 26, 2022, 15:52

The bcSubset function does not take into account some particularities of Spatial objects. If we are interested in eliminating cells from a BC object using bcSubset, we should also delete these cells from the coordinates slot (which is a Spatial-specific slot and can be found here: `bc@SeuratInfo$images$slice@coordinates`) If not, the function still works, but not eliminating these cells has an effect on other downstream functions, such as bcSignatures.

**Comment by SGMartin** [comment]
I'll handle this one
