### ISSUE TITLE
Error about GenerateGenesets

### ISSUE THREAD

**Issue by simaxiaoyao** [cnio-bu/beyondcell#129]
> gs <- GenerateGenesets(SSc)
Reading gmt file...
Error in x[1] : object of type 'S4' is not subsettable
or
> gs <- GenerateGenesets(PSc)
Reading gmt file...
Error in x[1] : object of type 'S4' is not subsettable

I just rum the code with the tutorial, but when I run 'gs <- GenerateGenesets(SSc)' or 'gs <- GenerateGenesets(PSc)', some errors happens. Could you tell me how solve this error?

**Comment by CrazyOrange233** [comment]
I had the same problem when I was using the R package, did you solve it?

**Comment by SGMartin** [comment]
Solved!

**Comment by SGMartin** [comment]
Hi @YongguangWei 

To address your issue we need a couple of details:

1. Which beyondcell version you are using at the moment.
2. A minimal code snippet that triggers the error, so that we may attempt to reproduce it.

Yours

**Comment by YongguangWei** [comment]
1. The version of r package "beyondcell" was 2.2.1 version.
2. Code: >GetCollection(SSc, n.genes = 250, mode = c("up", "down"))
          >gs <- GenerateGenesets(PSc)
          Reading gmt file...
          Error in x[1] : object of type 'S4' is not subsettable

**Comment by SGMartin** [comment]
It seems from your code that you are trying to load the PSc collection using GenerateGenesets instead of GetCollection.

PSc and SSc are predefined collections and thus, you can load both of them the same way using `GetCollection`. GenerateGenesets is now reserved for loading genesets from a gmt file.

**Comment by YongguangWei** [comment]
¡Muchas gracias!

**Comment by SGMartin** [comment]
Marked as solved
