### ISSUE TITLE
Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters): function 'as_cholmod_sparse' not provided by package 'Matrix'

### ISSUE THREAD

**Issue by wuyilin1234** [cnio-bu/beyondcell#142]
when I run this：bc <- bcUMAP(bc, pc = 10, k.neighbors = 4, res = 0.2)；meeting error ：Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters): function 'as_cholmod_sparse' not provided by package 'Matrix'.   how can i solve it?   thanks

**Comment by mj-jimenez** [comment]
Hi @wuyilin1234 sorry for the late response. 

I think this is a compatibility issue with the new Matrix package version. Please check if you have version 1.6-2 installed. If so, downgrade to 1.6-1 and try again.

Could you please send your session info? 
Thanks!

**Comment by mj-jimenez** [comment]
This has been solved in the beyondcell 2.2.1 release.
