### ISSUE TITLE
Error in GenerateGenesets(PSc)

### ISSUE THREAD

**Issue by AcetylCoALab** [cnio-bu/beyondcell#154]
gs <- GenerateGenesets(PSc)
Error in GenerateGenesets(PSc) : 
  no slot of name "up_genes" for this object of class "geneset"

**Comment by SGMartin** [comment]
Hi @AcetylCoALab 

PSc is a default collection in beyondcell and thus, you should use `GetCollection` If you want to load it. `GenerateGenesets` is for .gmt files.
