### ISSUE TITLE
bcScore/bcMerge/bcRecompute errors when using just 1 signature

### ISSUE THREAD

**Issue by Fryman93** [cnio-bu/beyondcell#21]
Hello, I ran into some issues with the bcScore, bcMerge, and bcRecompute functions.

When I tried inputting my own GMT files/functional signatures to a beyondcell object (bcScore/bcMerge) and then run bcRecompute, I get an error:

Error in bc@data[x, cells] : subscript out of bounds

This might have to do with how R tries to handle one-row matrices as vectors, causing downstream problems along the way such as creating unequal metacolumns. Would you be able to take a look at this?

**Comment by mj-jimenez** [comment]
Hi,
Thanks for rising this issue! Yes, when there is only one signature, R tries to simplify the matrix into a vector, producing errors along the way. We are fixing this issue in Beyondcell's [developing](https://github.com/cnio-bu/beyondcell/tree/developing) branch.
