### ISSUE TITLE
questions of PSc and SSc

### ISSUE THREAD

**Issue by QSong-github** [cnio-bu/beyondcell#30]
I would like to know how you identify the drug perturbation (PSc) and the drug sensitivity (SSc)? I am a little confused about this, since your tool starts with these. 
Thanks!

**Comment by SGMartin** [comment]
Hi @QSong-github 

Both collections of signatures are derived from linear models, the differences being the data sources:

1. PSc: We mine the CLUE/LINCS drug perturbation collection. In this case, the signatures capture the transcriptomic differences between perturbed/unperturbed cells.
2. SSc: These are mined from multiple pharmacogenomics assays such as CTRP or GDSC. Briefly, we collect genes whose expression changes according to the susceptibility to a given compound.
