### ISSUE TITLE
bcAddMetaData doesn't allow for existing columns to be replaced

### ISSUE THREAD

**Issue by Fryman93** [cnio-bu/beyondcell#33]
Hi, 

Could you edit the bcAddMetaData function so that if some metadata columns with identical names already exist in bc@meta.data, the function simply removes and replaces the existing relevant columns (similar to how Seurat::AddMetaData works).

Thank you,
Lucas

**Comment by mj-jimenez** [comment]
Thanks, your suggestion has been added to the code!
