### ISSUE TITLE
Make the regression step mandatory

### ISSUE THREAD

**Issue by tdido** [cnio-bu/beyondcell#4]
In GitLab by @cfustero on Nov 27, 2020, 13:22

As the number of features per cell seems to _always_ influence the results (generating "feature-poor" clusters). And also, the residuals allow us to obtain comparable metrics for all drugs, the bcRegressOut step should be mandatory in order to obtain the signature statistics.

Users should follow these steps for a correct analysis of their samples:
1) Compute BCS 
2) Compute UMAP 
3) Check clustering and look for unwanted sources of variation (bcClusters function) 
4) Regress out unwanted sources of variation
5) Recompute UMAP
6) Obtain signature's statistics

**Comment by SGMartin** [comment]
We'll leave it to the user. It should be done on most instances but we don't feel it should not be hardcoded.
