### ISSUE TITLE
Error in bcUMAP

### ISSUE THREAD

**Issue by laumtnezg** [cnio-bu/beyondcell#49]
bcUMAP raises an error when add.DSS = TRUE

**Comment by mj-jimenez** [comment]
Thanks Laura and Santi. 

The error is happening in **developing** branch after updating `DSS` and converting it to a `geneset` object. Now, any function with `add.DSS` breaks when this argument is set to `TRUE`. 

A reproducible example here:

```R
# First 5 IDs in SSc collection
ids <- c("sig-20879", "sig-20880", "sig-20881", "sig-20882", "sig-20883")

# Generate small geneset
ssc <- GetCollection(SSc, n.genes = 100, mode = c("up", "down"),
                     filters = list(IDs = ids), include.pathways = FALSE)

# Fake matrix
genes <- unique(unlist(ssc@genelist))
mtx <- scater::mockSCE(ngenes = length(genes), ncells = 50)
mtx <- mtx@assays@data$counts
rownames(mtx) <- genes

# Beyondcell object
bc <- bcScore(mtx, ssc, expr.thres = 0.1)

# UMAP
bc <- bcUMAP(bc, pc = NULL, add.DSS = TRUE)
```
```
Error in DSS[[1]] : this S4 class is not subsettable
```

The best workaround I can think is to replace `DSS` by `DSS@info` in these 2 functions:

- bcUMAP
- bcRegressOut

**Comment by SGMartin** [comment]
Let me fix this myself.

**Comment by mj-jimenez** [comment]
Thanks Santi! Let me contribute, as I really need this working in order to write the tests.
