### ISSUE TITLE
can not find the object "path_to_sc"

### ISSUE THREAD

**Issue by Chonghui-Liu** [cnio-bu/beyondcell#54]
when I run Beyondcell following the [analysis workflow] tutorials，I got an error. Please tell me where is the object "path_to_sc"

**Comment by mj-jimenez** [comment]
Hi Chonghui-Liu,

`path_to_sc` is not a preloaded object, it is just our way to name the actual path to a single-cell object in your machine. But it is true that it leads to confusion and should be written between quotes.

I am sorry for the inconvenience, if you want to run the tutorial you can download the single-cell object from this [link](https://zenodo.org/record/4438620#.Y3IuyC8w0UE).

**Comment by Chonghui-Liu** [comment]
Ok, I see. Thank you for your reply.

**Comment by SGMartin** [comment]
Marking this one as resolved.
