### ISSUE TITLE
Can beyondcell package be installed under windows system?

### ISSUE THREAD

**Issue by Phoenix12580** [cnio-bu/beyondcell#68]
Thank you very much for providing such a great tool!
I tried to install beyondcell in R 4.2.1 under windows， but failed.

**Comment by SGMartin** [comment]
Hi @Phoenix12580 

Thanks for you kind words. Beyondcell is compiled via bioconda's automatic builder. By default, It targets macOS (non ARM), Linux and Windows, but we don't test the latest extensively.  Let us perform a few test and we will get back to you ASAP. 

In the meantime, could you paste your 

```
conda env export 
```

so we may take a closer look at what's actually pulled in your case.

**Comment by Phoenix12580** [comment]
Thanks you very much, I am sorry.
I did not use bioconda. I tried to install beyondcell in Rstudio.  

devtools::install_github("cnio-bu/beyondcell",dependencies = T)

**Comment by Phoenix12580** [comment]
Thank you very much for your reply, looking forward to new works.
