### ISSUE TITLE
I have the same problem Imputing normalized BCS...

### ISSUE THREAD

**Issue by Phoenix12580** [cnio-bu/beyondcell#83]
Can I use other scRNA-seq imputation tools to the raw data and then input it into Beyondcell? Thank you very much.

**Comment by SGMartin** [comment]
Beyondcell requieres a normalized single cell matrix. Whether the aforementioned matrix has been imputed or not should not matter.  However, keep in mind that beyondcell's imputation happens over beyondcell scores and not over gene expression.

**Comment by Phoenix12580** [comment]
> Beyondcell requieres a normalized single cell matrix. Whether the aforementioned matrix has been imputed or not should not matter. However, keep in mind that beyondcell's imputation happens over beyondcell scores and not over gene expression.

Thank you very much
